### ISSUE TITLE
Massive performance hit from GSuiteStrategy

### ISSUE THREAD

**Issue by nicolaibaaring** [rezozero/canonical-email#4]
I implemented this package and realized that it had a massive performance hit on the application. So I investigated further and made the following profiling using PHPUnit as the runner. I ran multiple iterations but quickly found that the performance hit can be seen at a very low number of e-mail generations/checks. The emails are generated by Faker using `safeEmail`.

By running only 50 checks, the following results show.

All default strategies:

```
- LowercaseDomainStrategy
- GmailStrategy
- GSuiteStrategy
- OutlookStrategy

  Time:   21.88s
```

Removing individual strategies
```
- LowercaseDomainStrategy
- GmailStrategy
- GSuiteStrategy

  Time:   21.52s
```

```
- LowercaseDomainStrategy
- GmailStrategy

  Time:   0.36s
```

```
- LowercaseDomainStrategy

  Time:   0.36s
```

It shows that GSuiteStrategy is the culprit, so running with only this strategy has the following result:

```
- GSuiteStrategy

Time:   21.61s
```

And finally, the default set without the GSuiteStrategy:

```
- LowercaseDomainStrategy
- GmailStrategy
- OutlookStrategy

  Time:   0.36s
```

This renders GSuiteStrategy not useful due to the performance hit. 

Has anyone experienced the same and found any way to improve the numbers when using GSuiteStrategy?

**Comment by ambroisemaupate** [comment]
Hello @nicolaibaaring 

That's totally normal because Gmailk strategy is checking domain MX servers with `getmxrr($domain, $mxHosts)` method.

It's a DNS lookup for each email domain name. It's important because a Gmail email with Workspace can be configured with any domain, so we need to check MX to ensure canonical email.

**Comment by nicolaibaaring** [comment]
Yes. That's what I saw. Is this a useful strategy for your cases or have you found ways to use or improve it? 
I'm by now considering not applying it - first of all because I can't have that performance hit, but also because I realized that users who have Google Workspace and since change provider, they will actually not be recognized by their canonical e-mail.

**Comment by ambroisemaupate** [comment]
If this is too much latency for your case, you can strictly use:

- LowercaseDomainStrategy
- GmailStrategy
- OutlookStrategy

and ignore `GSuiteStrategy`, GSuite strategy applies Gmail rules to any domain using Gmail servers. So if your application can survive if users create multiple accounts with one email coming from Google Workspace you should disable this strategy. Or find another way to ensure user unicity like phone number verification, or maybe forbid `+` character in emails (event if it's a bad practice).
